// Generated by wrangler
// After running `npx wrangler types` or `npx wrangler d1 create`

interface CloudflareEnv {
    grepbase_db: D1Database;
    grepbase_cache: KVNamespace;
    ANALYTICS: AnalyticsEngineDataset;
    GITHUB_TOKEN?: string;
}
